### PR TITLE
Define uint64 duality once

### LINKED ISSUE #229: Section on I-JSON seems to confusingly redefine uint64
The section on I-JSON notes serialization concerns about 64-bit numbers that might be required for protocols like QUIC or HTTP/3.

It then says:

> Concretely, the following definition of uint64 should override the original and (web-based) tools should take into account that a uint64 field can be either a number or string.

> uint64 = text / uint .size 8

I find this confusing. This document defines a custom `unit64` itself. It's not entirely clear when the above override applies or not.

### PR DESCRIPTION
**Pull request by LPardue**
Closes #229

### CODE REVIEW

**Review by marten-seemann — COMMENTED** [review]
I don’t like this change. The CDDL is supposed to be an independent representation of the data, and now the quirks of one serialization are bleeding into this.

**Comment by LPardue** [comment]
That's fair. But that's effectively what we've already been saying all along - it was just buried in a section about I-JSON. We have an interop issue if people miss this section. E.g. with no way to signal I-JSON, if I pass you a JSON qlog file with a large GREASE value encoded with a string and you try to parse it as a uint64 ... 💥. A quiet fail is also bad, being unable to represent data values (or to parse them) is a way to hide data within a connection that might be expected to be observable.

Things are leaky. CDDL explains that in https://www.rfc-editor.org/rfc/rfc8610#appendix-E. Maybe there's some other way to explain that in the docs and I'm open to it but I don't have much inspiration.

**Comment by rmarx** [comment]
Discussed during editors meeting. 
Lucas will update this with new opinion about how we should handle uint64 in combo with CDDL.

**Comment by LPardue** [comment]
overtaken by #388

**Pull request closed without merging**
