### PR TITLE
add an environment field to the trace

### LINKED ISSUE #136: add a field to log the code version
With many iterations of my qlog implementation running in production now, it would be helpful if there was a way to tell which version of my code generated any particular qlog file (even better if qvis could display it somewhere).

I suggest adding an optional `code_version` to the `Trace` container. Implementations could fill this field with whatever they want. In quic-go, I'd probably use something like `quic-go $(git describe --long --dirty)`.

### PR DESCRIPTION
**Pull request by marten-seemann**
Fixes #136.

### CODE REVIEW

**Review by lnicco — COMMENTED** [review]
As @rmarx recommended on #136: could the `configuration` field above serve the same purpose? 

From the current text:
```
The configuration field can be viewed as a generic metadata field that tools can
fill with their own fields, based on per-tool logic. 
```

**Comment by LPardue** [comment]
I suggest a hybrid - put the environment field in the Configuration object.

**Comment by LPardue** [comment]
Although, https://github.com/quicwg/qlog/issues/187 suggests removing the configuration field. So we have a conflict of idealogies going on.,

**Review by rmarx — CHANGES_REQUESTED** [review]
See comment on #136

**Pull request closed without merging**
